version: "3"

services:
  postgres-database:
    image: postgres:11
    ports:
        - 5433:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: prova-estagio
    volumes:
        - prova-estagio-postgres-data:/var/lib/postgresql/data
  app:
    build: .
    environment:
        - DATABASE_HOST=postgres-database
        - DATABASE_PORT=5432
    ports:
      - "3000:3000"      
volumes:
    prova-estagio-postgres-data: